[package]
name = "heart"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
env_logger = "0.11.7"
log = "0.4.26"
quick-xml = "0.37.2"
lz4 = "1.28.1"
